export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  "Create a futuristic cityscape at dusk.",
    "Generate an image of an alien forest with glowing plants.",
    "Visualize a cyberpunk street scene at night.",
    "Design an underwater kingdom with diverse marine life.",
    "Imagine a steampunk airship in the clouds.",
    "Depict a post-apocalyptic landscape with overgrown ruins.",
    "Generate a portrait of a robot with human-like features.",
    "Create a surreal dreamscape with floating islands.",
    "Visualize a fantasy castle on a mountain peak.",
    "Design a bustling marketplace in a medieval town.",
    "Depict a serene Japanese garden in spring.",
    "Generate an image of a futuristic space station.",
    "Create an enchanted forest with mythical creatures.",
    "Visualize a vibrant coral reef with exotic fish.",
    "Design a high-tech laboratory with advanced gadgets.",
    "Depict a tranquil beach at sunset.",
    "Generate a bustling metropolis in the year 3000.",
    "Create a mystical cave with glowing crystals.",
    "Visualize a historic battle scene with knights.",
    "Design a quaint village in the countryside.",
    "Depict a snowy mountain landscape with a cozy cabin.",
    "Generate an image of an ancient temple in the jungle.",
    "Create a futuristic car racing through neon-lit streets.",
    "Visualize an intergalactic spaceship docking at a station.",
    "Design a whimsical treehouse village.",
    "Depict a serene desert oasis at dusk.",
    "Generate a scene of a bustling alien marketplace.",
    "Create an image of a futuristic sports arena.",
    "Visualize a medieval castle siege.",
    "Design a picturesque European village.",
    "Depict a mysterious island shrouded in mist.",
    "Generate an image of a high-tech futuristic city.",
    "Create a magical library with floating books.",
    "Visualize an ancient civilization on a distant planet.",
    "Design a serene lakeside retreat.",
    "Depict a bustling train station in the future.",
    "Generate an image of a hidden waterfall in the jungle.",
    "Create a fantasy realm with dragons and wizards.",
    "Visualize a peaceful zen garden.",
    "Design an intricate maze with hidden treasures.",
    "Depict a vibrant carnival at night.",
    "Generate an image of a futuristic robotic pet.",
    "Create a mystical landscape with floating lanterns.",
    "Visualize a historic city during a festival.",
    "Design a modern skyscraper with a unique shape.",
    "Depict a serene countryside with rolling hills.",
    "Generate an image of an underwater alien city.",
    "Create a futuristic train traveling through a dense forest.",
    "Visualize a bustling harbor in a fantasy world.",
    "Design a magical tree with glowing fruits."
]